### ISSUE TITLE
Character rendering (F11) gives transparent outline.

### ISSUE THREAD

**Issue by chlorine03** [bbepis/BepInEx#10]
As the title has stated. I've tried both Legacy and Alphashot, however after exporting, the image would end up with no outline (it's as if there's an outline transparency option in-game and you've set it to 0). Would you please be so kind as to look at this issue? I'm wondering if it's a problem on my end or not.

**Comment by bbepis** [comment]
Outlines are a shader issue. Neither legacy or alphashot renderers have the capability to fix this, though. More research into how the game uses the shaders is required before we can actually figure out why it's not working. Sorry for that.

**Comment by bbepis** [comment]
Pressed the wrong button, sorry. I'll leave it open since it needs to be fixed eventually

**Comment by bbepis** [comment]
AlphaShot2 seems to be the best workaround for this, which does capture the outline. Although it's not a proper solution, it seems to be the best for now.
