### ISSUE TITLE
verson 3.1 patching issue report

### ISSUE THREAD

**Issue by Testrfr2018** [bbepis/BepInEx#18]
First of all, I greatly appreciate bbepis's good work.
Then about the feedback:
After patched, I found out that I can't load a save in the main game or studio game.
To be specific, the 'Yes' button didn't work.
Also, in the studio game, some rendering function in the config didn't work too.
I test out that there's something wrong with the UnityEngine.dll.

Sorry for my poor English, and that's all. Thank you!

**Comment by 8246asd** [comment]
Please excuse about my poor grammar:
I've got the latest BepInEx.3.1 and BepisPlugins.r2 and run into the same problem with Testrfr2018.
 When I try to load a save, the yes button just don't work,  whether  I do a in-game loading or at title, the YES button won't work.
I found that if I make a save at the start of the game(first night when you have to put characters in the school) the YES button do works, but just for that save only and the rest are still dead.

Thanks for your time, these works of yours does really good job and really help us a lot.

**Comment by bbepis** [comment]
These seem to be fixed in plugin pack r3
Also please put your issues about the plugins [here](https://github.com/bbepis/BepisPlugins/issues), this repo should be about the patcher itself
