### ISSUE TITLE
Problem with ScreenCap Plugin 1.1

### ISSUE THREAD

**Issue by SiTWulf** [bbepis/BepInEx#5]
Hi. (English is not my native language)
The last version of the ScreenCap Plugin ignore the Color Shade when you use it.

How to:
Active or Not Color Shader (F6),  try to make some ScreenShots using the Plugin ScreenCap (F9, F11), all the screencaps uses the color shader activate.

If i use the old version 1.01 of the plugin ScrenCap.dll i not get this error.

**Comment by bbepis** [comment]
I've just fixed this, will be released with v1.2.
