### ISSUE TITLE
Problems with the Console Window

### ISSUE THREAD

**Issue by SiTWulf** [bbepis/BepInEx#6]
Hi. (English is not my native language)

Sometimes in Windowed mode, the Console Window appears over the Game window. 
And if you use any program to make Borderless the game window console appears always over the game window.

The problems looks belong to the name of the new Console Window, is exact name of the Main Game Window Name, and the borderless program make the 2 window borderless, first the game window and after the console window, making the second window over the game window.

**Comment by bbepis** [comment]
I've removed the console, and replaced it with an ingame developer console. This'll be released with v1.3.
