### ISSUE TITLE
Nipple Gloss Slider Issue

### ISSUE THREAD

**Issue by josewh** [bbepis/BepInEx#9]
There's a problem with Nipple Gloss Slider. 
- It resets when I change to other menu and come back to nipple menu.
- Can't save the value too, even I only set the nipple gloss and save the character right after it, still loaded with 0 nipple gloss. 
- Character I made before patch is loaded fine and not reset if Im going to nipple menu. re-saved also fine.
- Seems like the trouble it only save the last value if loaded. so if I load character with 100 nipple gloss and change it, change menu and come back, it resets to 100.

**Comment by bbepis** [comment]
Alright, I have not been able to find the reason as to why this is happening. It uses the same methods as the other sliders to change value, so it seems that there's something extra hidden somewhere keeping it like this. I've locked the gloss slider for now; it seems to be retaining value now, although it's not the best solution.

**Comment by josewh** [comment]
Well atleast we can change it's fine, until we find out what's causing it. and gloss/color slider isn't something to much worrying about by being not having <0 or >100 most of the time it looks weird.

**Comment by bbepis** [comment]
As it turns out, it's a bug on Illusion's side, which is fixed in the maker version 2.0. I've unlocked the nipple gloss slider again as a result.
